-- Named save-block addresses. Loaded by VersionCheck after the version file, so
-- saveData1 / saveData2 are already set for the running game version.
-- EVDL side: save_data[N] = saveData1 + N, save_data2[N] = saveData2 + N.
-- Keep names in sync with KH1-EVDL-TOOLS/save_data_labels.json.

-- save_data1
EOTW_ROOM_FLAGS_FIXED           = saveData1 + 0x00D
NAVI_GUMMI_OBTAINED             = saveData1 + 0x040 -- RANDO ONLY
EARTHSHINE_IN_BAG               = saveData1 + 0x041 -- RANDO ONLY
DI_DEFEAT_RIKU_DAY_1_REWARD     = saveData1 + 0x042 -- RANDO ONLY
DI_DEFEAT_TRIO_DAY_2_REWARD     = saveData1 + 0x043 -- RANDO ONLY
DI_GATHER_COCONUT_REWARD        = saveData1 + 0x044 -- RANDO ONLY
DI_KAIRI_POTION_DAY_1_REWARD    = saveData1 + 0x045 -- RANDO ONLY
DI_KAIRI_HI_POTION_DAY_1_REWARD = saveData1 + 0x046 -- RANDO ONLY
DI_RACE_RIKU_DAY_2_REWARD       = saveData1 + 0x047 -- RANDO ONLY
DI_KAIRI_POTION_DAY_2_REWARD    = saveData1 + 0x048 -- RANDO ONLY
DI_KAIRI_HI_POTION_DAY_2_REWARD = saveData1 + 0x049 -- RANDO ONLY
DAY_2_MATERIALS_REQUIRED        = saveData1 + 0x04A -- RANDO ONLY
HOMECOMING_MATERIALS_REQUIRED   = saveData1 + 0x04B -- RANDO ONLY
SHORTEN_GO_MODE                 = saveData1 + 0x04C -- RANDO ONLY
HOMECOMING_ARRIVAL_PENDING      = saveData1 + 0x04D -- RANDO ONLY
INTERACT_IN_BATTLE              = saveData1 + 0x04E -- RANDO ONLY
DIVE_TO_THE_HEART_WEAPON_CHOSEN = saveData1 + 0x100
DIVE_TO_THE_HEART_WEAPON_GIVEN_UP = saveData1 + 0x101
LEON_GIFT_GIVEN                 = saveData1 + 0x10D
KEYBLADE_EXPLANATION            = saveData1 + 0x10E
AERITH_GIFT_GIVEN               = saveData1 + 0x10F
TRINITY_TUTORIAL_SEEN           = saveData1 + 0x110
WATERWAY_CUTSCENE_FLAG          = saveData1 + 0x112
CID_PREREQUISITE                = saveData1 + 0x11A
GEPPETTO_GIFT_GIVEN             = saveData1 + 0x11C
OPPOSITE_TRIGGER                = saveData1 + 0x11D
NAVI_G_PIECE_2_BAG_SNAPSHOT     = saveData1 + 0x120
NATURESPARK_IN_BAG              = saveData1 + 0x128
WATERGLEAM_IN_BAG               = saveData1 + 0x129
FIREGLOW_IN_BAG                 = saveData1 + 0x12A
EARTHSHINE_RETURNED             = saveData1 + 0x12B
NATURESPARK_RETURNED            = saveData1 + 0x12C
WATERGLEAM_RETURNED             = saveData1 + 0x12D
FIREGLOW_RETURNED               = saveData1 + 0x12E
ALL_SUMMON_GEMS_RETURNED        = saveData1 + 0x12F
CID_BLUEPRINT_GIVEN             = saveData1 + 0x130
AERITH_BLUEPRINT_GIVEN          = saveData1 + 0x131
YUFFIE_BLUEPRINT_GIVEN          = saveData1 + 0x132
LEON_BLUEPRINT_GIVEN            = saveData1 + 0x133
CACTUAR_BLUEPRINT_GIVEN         = saveData1 + 0x134
CHOCOBO_BLUEPRINT_GIVEN         = saveData1 + 0x135
HYPERION_BLUEPRINT_GIVEN        = saveData1 + 0x136
GEPPETTO_VISITS                 = saveData1 + 0x137
MAGICIAN_STUDY_ALL_ARTS_ITEMS   = saveData1 + 0x138
MAGICIAN_STUDY_ALL_LV1_MAGIC    = saveData1 + 0x139
MAGICIAN_STUDY_ALL_LV3_MAGIC    = saveData1 + 0x13A
EW33_SECOND_VISIT               = saveData1 + 0x141
AW05_SET13_INTRO_SEEN           = saveData1 + 0x207
HAS_FOOTPRINTS                  = saveData1 + 0x208
HAS_CLAW_MARKS                  = saveData1 + 0x209
HAS_STENCH                      = saveData1 + 0x20A
HAS_ANTENNA                     = saveData1 + 0x20B
EARLY_BLIZZARD_GIVEN            = saveData1 + 0x22B
PUPPIES_RETURNED_10             = saveData1 + 0x231
PUPPIES_RETURNED_20             = saveData1 + 0x232
PUPPIES_RETURNED_30             = saveData1 + 0x233
PUPPIES_RETURNED_40             = saveData1 + 0x234
PUPPIES_RETURNED_50             = saveData1 + 0x235
PUPPIES_RETURNED_60             = saveData1 + 0x236
PUPPIES_RETURNED_70             = saveData1 + 0x237
PUPPIES_RETURNED_80             = saveData1 + 0x238
PUPPIES_RETURNED_90             = saveData1 + 0x239
PUPPIES_RETURNED_99             = saveData1 + 0x23A
PUPPIES_10_REWARD_GIVEN         = saveData1 + 0x23C
PUPPIES_20_REWARD_GIVEN         = saveData1 + 0x23D
PUPPIES_30_REWARD_GIVEN         = saveData1 + 0x23E
PUPPIES_40_REWARD_GIVEN         = saveData1 + 0x23F
PUPPIES_50_REWARD_GIVEN         = saveData1 + 0x240
PUPPIES_60_REWARD_GIVEN         = saveData1 + 0x241
PUPPIES_70_REWARD_GIVEN         = saveData1 + 0x242
PUPPIES_80_REWARD_GIVEN         = saveData1 + 0x243
PUPPIES_90_REWARD_GIVEN         = saveData1 + 0x244
PUPPIES_99_REWARD_GIVEN         = saveData1 + 0x245
PUPPY_REWARD_PENDING            = saveData1 + 0x247
OC_CLOUD_SONIC_BLADE_EVENT      = saveData1 + 0x302
OC_ENTRY_PASS_STATE             = saveData1 + 0x30E
OC_HERCULES_CUP_DEFEAT_CLOUD    = saveData1 + 0x346
OC_HADES_CUP_DEFEAT_YUFFIE      = saveData1 + 0x348
OC_GRAVITY_REWARD_GIVEN         = saveData1 + 0x35F
OC_ICE_TITAN_DEFEATED           = saveData1 + 0x369
SEPHIROTH_FLAG                  = saveData1 + 0x36A
OC_CLOUD_VS_SEPHIROTH_CUTSCENE  = saveData1 + 0x3B2
CAN_PROGRESS_DI_DAY_2           = saveData1 + 0x400
DI_DRINKING_WATER_TAKEN         = saveData1 + 0x407
DI_COVE_MUSHROOM_ZIPLINE_DAY2   = saveData1 + 0x40A
DI_COVE_MUSHROOM_SMALL_CAVE_DAY2 = saveData1 + 0x40B
DI_LOG_COUNT                    = saveData1 + 0x40C
DI_CLOTH_COUNT                  = saveData1 + 0x40D
DI_ROPE_COUNT                   = saveData1 + 0x40E
DI_DAY2_SUPPLY_COUNT_40F        = saveData1 + 0x40F
DI_SEASHORE_SEAGULL_EGG_DAY2    = saveData1 + 0x410
DI_DAY2_SUPPLY_COUNT_411        = saveData1 + 0x411
CAN_PROGRESS_DI_DAY_1           = saveData1 + 0x412
RIKU_RACE_COUNT                 = saveData1 + 0x422
DI_SEASHORE_FISH_1_DAY2         = saveData1 + 0x426
DI_SEASHORE_FISH_2_DAY2         = saveData1 + 0x427
DI_SEASHORE_FISH_3_DAY2         = saveData1 + 0x428
DI_SECRET_PLACE_MUSHROOM_DAY2   = saveData1 + 0x429
DI_SEASHORE_ROPE_DAY1           = saveData1 + 0x42B
DI_SEASHORE_LOG_RIKU_ISLAND_DAY1 = saveData1 + 0x432
DI_SEASHORE_LOG_UNDER_BRIDGE_DAY1 = saveData1 + 0x433
DI_SEASHORE_CLOTH_DAY1          = saveData1 + 0x434
SORA_VS_RIKU_SORA_SCORE         = saveData1 + 0x436
SORA_VS_RIKU_RIKU_SCORE         = saveData1 + 0x438
KAIRI_GIVES_HINT                = saveData1 + 0x444
KAIRI_SAYS_YOURE_HOPELESS       = saveData1 + 0x445
DI_RACE_REMATCH_PENDING         = saveData1 + 0x456
HB_LIBRARY_AERITH_CURE          = saveData1 + 0x50E
HB_LIBRARY_BELLE_DIVINE_ROSE    = saveData1 + 0x50F
DJ_TENT_JANE_SCENE_STATE        = saveData1 + 0x606
SLIDE_1_TURNED_IN               = saveData1 + 0x607
SLIDE_2_TURNED_IN               = saveData1 + 0x608
SLIDE_3_TURNED_IN               = saveData1 + 0x609
SLIDE_4_TURNED_IN               = saveData1 + 0x60A
SLIDE_5_TURNED_IN               = saveData1 + 0x60B
SLIDE_6_TURNED_IN               = saveData1 + 0x60C
DJ_CLIFF_GORILLAS_SAVED         = saveData1 + 0x60D
DJ_TREE_HOUSE_GORILLAS_SAVED    = saveData1 + 0x60E
DJ_CAMP_GORILLAS_SAVED          = saveData1 + 0x60F
DJ_BAMBOO_THICKET_GORILLAS_SAVED = saveData1 + 0x610
DJ_CLIMBING_TREES_GORILLAS_SAVED = saveData1 + 0x611
SLIDES_VIEWED_COUNT             = saveData1 + 0x612
SLIDE_1_VIEWED                  = saveData1 + 0x613
SLIDE_2_VIEWED                  = saveData1 + 0x614
SLIDE_3_VIEWED                  = saveData1 + 0x615
SLIDE_4_VIEWED                  = saveData1 + 0x616
SLIDE_5_VIEWED                  = saveData1 + 0x617
SLIDE_6_VIEWED                  = saveData1 + 0x618
SLIDE_1_LOCATION_TAKEN          = saveData1 + 0x628
SLIDE_2_LOCATION_TAKEN          = saveData1 + 0x629
SLIDE_3_LOCATION_TAKEN          = saveData1 + 0x62A
SLIDE_4_LOCATION_TAKEN          = saveData1 + 0x62B
SLIDE_5_LOCATION_TAKEN          = saveData1 + 0x62C
SLIDE_6_LOCATION_TAKEN          = saveData1 + 0x62D
TORN_PAGES_AVAILABLE            = saveData1 + 0x800
POOH_RARE_NUTS_TURNED_IN        = saveData1 + 0x801
POOH_RARE_NUT_1_STATE           = saveData1 + 0x802
POOH_RARE_NUT_2_STATE           = saveData1 + 0x803
POOH_RARE_NUT_3_STATE           = saveData1 + 0x804
POOH_RARE_NUT_4_STATE           = saveData1 + 0x805
POOH_RARE_NUT_5_STATE           = saveData1 + 0x806
POOH_RARE_NUT_REWARD_PENDING    = saveData1 + 0x807
POOH_OWL_CHEER                  = saveData1 + 0x80F
POOH_TORN_PAGE_1_CONVERTED      = saveData1 + 0x810
POOH_TORN_PAGE_2_CONVERTED      = saveData1 + 0x811
POOH_TORN_PAGE_3_CONVERTED      = saveData1 + 0x812
POOH_TORN_PAGE_4_CONVERTED      = saveData1 + 0x813
POOH_TORN_PAGE_5_CONVERTED      = saveData1 + 0x814
POOH_PROGRESS_2                 = saveData1 + 0x820
POOH_AREA_2_PROGRESS            = saveData1 + 0x822
POOH_AREA_3_PROGRESS            = saveData1 + 0x824
POOH_AREA_4_PROGRESS            = saveData1 + 0x826
POOH_AREA_5_PROGRESS            = saveData1 + 0x828
POOH_AREA_6_PROGRESS            = saveData1 + 0x82A
STORY_PROGRESS_GLOBAL           = saveData1 + 0x900
DIVE_TO_THE_HEART_PROGRESS      = saveData1 + 0x901
DESTINY_ISLANDS_PROGRESS        = saveData1 + 0x902
DISNEY_CASTLE_PROGRESS          = saveData1 + 0x903
TRAVERSE_TOWN_PROGRESS          = saveData1 + 0x904
DEEP_JUNGLE_PROGRESS            = saveData1 + 0x905
OLYMPUS_COLISEUM_PROGRESS       = saveData1 + 0x906
WONDERLAND_PROGRESS             = saveData1 + 0x907
AGRABAH_PROGRESS                = saveData1 + 0x908
MONSTRO_PROGRESS                = saveData1 + 0x909
ATLANTICA_PROGRESS              = saveData1 + 0x90A
HALLOWEEN_TOWN_PROGRESS         = saveData1 + 0x90C
NEVERLAND_PROGRESS              = saveData1 + 0x90D
HOLLOW_BASTION_PROGRESS         = saveData1 + 0x90E
END_OF_THE_WORLD_PROGRESS       = saveData1 + 0x90F
TRAVERSE_TOWN_PROGRESS_2        = saveData1 + 0x912

-- save_data2
PREVIOUS_WORLD                  = saveData2 + 0x000
PREVIOUS_AREA                   = saveData2 + 0x001
PREVIOUS_SET                    = saveData2 + 0x002
DIALOG_STATE                    = saveData2 + 0x003
EVENT_POSITION_X                = saveData2 + 0x00E
EVENT_POSITION_Y                = saveData2 + 0x010
EVENT_POSITION_Z                = saveData2 + 0x012
TRINITY_EVENT_PARAM             = saveData2 + 0x018
TRINITY_UNLOCK                  = saveData2 + 0x01B
CURRENT_WORLD                   = saveData2 + 0x01C
MAGIC_FLAGS                     = saveData2 + 0x01E
BLIZZARD_MAGIC_LEVEL            = saveData2 + 0x01F
THUNDER_MAGIC_LEVEL             = saveData2 + 0x020
CURE_MAGIC_LEVEL                = saveData2 + 0x021
GRAVITY_MAGIC_LEVEL             = saveData2 + 0x022
STOP_MAGIC_LEVEL                = saveData2 + 0x023
AERO_MAGIC_LEVEL                = saveData2 + 0x024
BLUE_TRINITIES_ACTIVATED        = saveData2 + 0x066
RED_TRINITIES_ACTIVATED         = saveData2 + 0x068
GREEN_TRINITIES_ACTIVATED       = saveData2 + 0x069
YELLOW_TRINITIES_ACTIVATED      = saveData2 + 0x06A
WHITE_TRINITIES_ACTIVATED       = saveData2 + 0x06B
WATERWAY_GATE                   = saveData2 + 0x06D
HB_LIBRARY_GREEN_TRINITY        = saveData2 + 0x07C
WATERWAY_TRINITY                = saveData2 + 0x0B1
TT_SAFE_POSTCARD                = saveData2 + 0x0B7
OPPOSITE_STATE                  = saveData2 + 0x0B8
TT_GIZMO_SHOP_SWITCHES          = saveData2 + 0x0BD
POSTCARDS_MAILED                = saveData2 + 0x0BF
EVIDENCE_BOXES_OPENED           = saveData2 + 0x10E
DJ_RECIPE_CARD_110_TAKEN        = saveData2 + 0x110
DJ_RECIPE_CARD_114_TAKEN        = saveData2 + 0x114
DJ_RECIPE_CARD_115_TAKEN        = saveData2 + 0x115
DJ_CAMP_ETHER_EXPERIMENT        = saveData2 + 0x119
DJ_RECIPE_CARD_11A_TAKEN        = saveData2 + 0x11A
DJ_RECIPE_CARD_11B_TAKEN        = saveData2 + 0x11B
DJ_CAMP_HI_POTION_EXPERIMENT_ALT = saveData2 + 0x11E
DJ_CAMP_HI_POTION_EXPERIMENT    = saveData2 + 0x11F
DJ_CAMP_REPLICATION_EXPERIMENT  = saveData2 + 0x127
DJ_CLAYTON_FIX_FLAGS            = saveData2 + 0x12C
DJ_JUNGLE_SLIDER_50_FRUITS      = saveData2 + 0x135
DJ_JUNGLE_SLIDER_10_FRUITS      = saveData2 + 0x139
DJ_JUNGLE_SLIDER_20_FRUITS      = saveData2 + 0x13A
DJ_JUNGLE_SLIDER_30_FRUITS      = saveData2 + 0x13B
DJ_JUNGLE_SLIDER_40_FRUITS      = saveData2 + 0x13C
SAVED_FRUITS                    = saveData2 + 0x13E
POOH_ROOM_CABINET               = saveData2 + 0x143
POOH_ROOM_CHIMNEY               = saveData2 + 0x144
POOH_BOUNCING_SPOT_BREAK_LOG    = saveData2 + 0x145
POOH_BOUNCING_SPOT_FALL_THROUGH_TREE = saveData2 + 0x146
POOH_PROGRESS                   = saveData2 + 0x148
ATLANTICA_CLAMS                 = saveData2 + 0x1A9
OC_CUP_UNLOCK                   = saveData2 + 0x200
OC_PEGASUS_CUP_UNLOCK           = saveData2 + 0x201
OC_HERCULES_CUP_UNLOCK          = saveData2 + 0x202
OC_HADES_CUP_UNLOCK             = saveData2 + 0x203
OC_YELLOW_TRINITY_REMOVED       = saveData2 + 0x210
OC_GATES_PURPLE_JAR_AFTER_HADES = saveData2 + 0x213
HB_WATERWAY_SWITCHES            = saveData2 + 0x299
HB_LIBRARY_SHELVES              = saveData2 + 0x2AB
EMBLEM_COUNT                    = saveData2 + 0x2AD
HB_EMBLEM_PIECE_FLAME_TAKEN     = saveData2 + 0x2AE
HB_EMBLEM_PIECE_CHEST_TAKEN     = saveData2 + 0x2AF
HB_EMBLEM_PIECE_STATUE_TAKEN    = saveData2 + 0x2B0
HB_EMBLEM_PIECE_FOUNTAIN_TAKEN  = saveData2 + 0x2B1
HB_LIBRARY_BOOK                 = saveData2 + 0x2B4
EMBLEM_DOOR                     = saveData2 + 0x2BC
EMBLEM_DOOR_STATE_2             = saveData2 + 0x2BF
TRAVERSE_TOWN_WORLD_STATUS      = saveData2 + 0x2F0
WONDERLAND_WORLD_STATUS         = saveData2 + 0x2F1
OLYMPUS_COLISEUM_WORLD_STATUS   = saveData2 + 0x2F2
DEEP_JUNGLE_WORLD_STATUS        = saveData2 + 0x2F3
AGRABAH_WORLD_STATUS            = saveData2 + 0x2F4
ATLANTICA_WORLD_STATUS          = saveData2 + 0x2F5
HALLOWEEN_TOWN_WORLD_STATUS     = saveData2 + 0x2F6
NEVERLAND_WORLD_STATUS          = saveData2 + 0x2F7
HOLLOW_BASTION_WORLD_STATUS     = saveData2 + 0x2F8
END_OF_THE_WORLD_WORLD_STATUS   = saveData2 + 0x2F9
MONSTRO_WORLD_STATUS            = saveData2 + 0x2FA
TT_DOCK_POINTS                  = saveData2 + 0x2FF
DJ_DOCK_POINTS                  = saveData2 + 0x302
NL_DOCK_POINTS                  = saveData2 + 0x306
HB_DOCK_POINTS                  = saveData2 + 0x307
EOTW_DOCK_POINTS                = saveData2 + 0x308
WORLD_MAP_LINES                 = saveData2 + 0x312
WORLD_MAP_LINES_4               = saveData2 + 0x316
DOCK_POINTS_6_BACKUP            = saveData2 + 0x345
GIFT_TABLE_ITEM                 = saveData2 + 0x3C4
SPAWN_POINT                     = saveData2 + 0x448
DH01_SET_NUMBER                 = saveData2 + 0x46C
DH02_SET_NUMBER                 = saveData2 + 0x46D
DH03_SET_NUMBER                 = saveData2 + 0x46E
DH04_SET_NUMBER                 = saveData2 + 0x46F
DH05_SET_NUMBER                 = saveData2 + 0x470
DH06_SET_NUMBER                 = saveData2 + 0x471
DH07_SET_NUMBER                 = saveData2 + 0x472
DI01_SET_NUMBER                 = saveData2 + 0x473
DI02_SET_NUMBER                 = saveData2 + 0x474
DI03_SET_NUMBER                 = saveData2 + 0x475
DI04_SET_NUMBER                 = saveData2 + 0x476
DI05_SET_NUMBER                 = saveData2 + 0x477
DI06_SET_NUMBER                 = saveData2 + 0x478
DI07_SET_NUMBER                 = saveData2 + 0x479
DI08_SET_NUMBER                 = saveData2 + 0x47A
DI09_SET_NUMBER                 = saveData2 + 0x47B
DI10_SET_NUMBER                 = saveData2 + 0x47C
DI11_SET_NUMBER                 = saveData2 + 0x47D
DI12_SET_NUMBER                 = saveData2 + 0x47E
DC01_SET_NUMBER                 = saveData2 + 0x47F
DC02_SET_NUMBER                 = saveData2 + 0x480
DC03_SET_NUMBER                 = saveData2 + 0x481
DC04_SET_NUMBER                 = saveData2 + 0x482
DC05_SET_NUMBER                 = saveData2 + 0x483
DC06_SET_NUMBER                 = saveData2 + 0x484
DC07_SET_NUMBER                 = saveData2 + 0x485
DC08_SET_NUMBER                 = saveData2 + 0x486
DC09_SET_NUMBER                 = saveData2 + 0x487
TW01_SET_NUMBER                 = saveData2 + 0x488
TW02_SET_NUMBER                 = saveData2 + 0x489
TW03_SET_NUMBER                 = saveData2 + 0x48A
TW04_SET_NUMBER                 = saveData2 + 0x48B
TW05_SET_NUMBER                 = saveData2 + 0x48C
TW06_SET_NUMBER                 = saveData2 + 0x48D
TW07_SET_NUMBER                 = saveData2 + 0x48E
TW08_SET_NUMBER                 = saveData2 + 0x48F
TW09_SET_NUMBER                 = saveData2 + 0x490
TW10_SET_NUMBER                 = saveData2 + 0x491
TW11_SET_NUMBER                 = saveData2 + 0x492
TW12_SET_NUMBER                 = saveData2 + 0x493
TW13_SET_NUMBER                 = saveData2 + 0x494
TW14_SET_NUMBER                 = saveData2 + 0x495
TW15_SET_NUMBER                 = saveData2 + 0x496
TW16_SET_NUMBER                 = saveData2 + 0x497
TW17_SET_NUMBER                 = saveData2 + 0x498
TW18_SET_NUMBER                 = saveData2 + 0x499
TW19_SET_NUMBER                 = saveData2 + 0x49A
TW20_SET_NUMBER                 = saveData2 + 0x49B
TW21_SET_NUMBER                 = saveData2 + 0x49C
TW22_SET_NUMBER                 = saveData2 + 0x49D
TW23_SET_NUMBER                 = saveData2 + 0x49E
TW24_SET_NUMBER                 = saveData2 + 0x49F
TW25_SET_NUMBER                 = saveData2 + 0x4A0
TW26_SET_NUMBER                 = saveData2 + 0x4A1
AW01_SET_NUMBER                 = saveData2 + 0x4A2
AW02_SET_NUMBER                 = saveData2 + 0x4A3
AW03_SET_NUMBER                 = saveData2 + 0x4A4
AW04_SET_NUMBER                 = saveData2 + 0x4A5
AW05_SET_NUMBER                 = saveData2 + 0x4A6
AW06_SET_NUMBER                 = saveData2 + 0x4A7
AW07_SET_NUMBER                 = saveData2 + 0x4A8
AW08_SET_NUMBER                 = saveData2 + 0x4A9
AW09_SET_NUMBER                 = saveData2 + 0x4AA
AW10_SET_NUMBER                 = saveData2 + 0x4AB
TZ01_SET_NUMBER                 = saveData2 + 0x4AC
TZ02_SET_NUMBER                 = saveData2 + 0x4AD
TZ03_SET_NUMBER                 = saveData2 + 0x4AE
TZ04_SET_NUMBER                 = saveData2 + 0x4AF
TZ05_SET_NUMBER                 = saveData2 + 0x4B0
TZ06_SET_NUMBER                 = saveData2 + 0x4B1
TZ07_SET_NUMBER                 = saveData2 + 0x4B2
TZ08_SET_NUMBER                 = saveData2 + 0x4B3
TZ09_SET_NUMBER                 = saveData2 + 0x4B4
TZ10_SET_NUMBER                 = saveData2 + 0x4B5
TZ11_SET_NUMBER                 = saveData2 + 0x4B6
TZ12_SET_NUMBER                 = saveData2 + 0x4B7
TZ13_SET_NUMBER                 = saveData2 + 0x4B8
TZ14_SET_NUMBER                 = saveData2 + 0x4B9
TZ15_SET_NUMBER                 = saveData2 + 0x4BA
TZ16_SET_NUMBER                 = saveData2 + 0x4BB
TZ17_SET_NUMBER                 = saveData2 + 0x4BC
TZ18_SET_NUMBER                 = saveData2 + 0x4BD
TZ19_SET_NUMBER                 = saveData2 + 0x4BE
TZ20_SET_NUMBER                 = saveData2 + 0x4BF
PO01_SET_NUMBER                 = saveData2 + 0x4C0
PO02_SET_NUMBER                 = saveData2 + 0x4C1
PO03_SET_NUMBER                 = saveData2 + 0x4C2
PO04_SET_NUMBER                 = saveData2 + 0x4C3
PO05_SET_NUMBER                 = saveData2 + 0x4C4
PO06_SET_NUMBER                 = saveData2 + 0x4C5
PO07_SET_NUMBER                 = saveData2 + 0x4C6
PO08_SET_NUMBER                 = saveData2 + 0x4C7
PO09_SET_NUMBER                 = saveData2 + 0x4C8
PO10_SET_NUMBER                 = saveData2 + 0x4C9
PO11_SET_NUMBER                 = saveData2 + 0x4CA
AL01_SET_NUMBER                 = saveData2 + 0x4CC
AL02_SET_NUMBER                 = saveData2 + 0x4CD
AL03_SET_NUMBER                 = saveData2 + 0x4CE
AL04_SET_NUMBER                 = saveData2 + 0x4CF
AL05_SET_NUMBER                 = saveData2 + 0x4D0
AL06_SET_NUMBER                 = saveData2 + 0x4D1
AL07_SET_NUMBER                 = saveData2 + 0x4D2
AL08_SET_NUMBER                 = saveData2 + 0x4D3
AL09_SET_NUMBER                 = saveData2 + 0x4D4
AL10_SET_NUMBER                 = saveData2 + 0x4D5
AL11_SET_NUMBER                 = saveData2 + 0x4D6
AL12_SET_NUMBER                 = saveData2 + 0x4D7
AL13_SET_NUMBER                 = saveData2 + 0x4D8
AL14_SET_NUMBER                 = saveData2 + 0x4D9
AL15_SET_NUMBER                 = saveData2 + 0x4DA
AL16_SET_NUMBER                 = saveData2 + 0x4DB
AL17_SET_NUMBER                 = saveData2 + 0x4DC
AL18_SET_NUMBER                 = saveData2 + 0x4DD
AL19_SET_NUMBER                 = saveData2 + 0x4DE
AL20_SET_NUMBER                 = saveData2 + 0x4DF
AL21_SET_NUMBER                 = saveData2 + 0x4E0
LM01_SET_NUMBER                 = saveData2 + 0x4E1
LM02_SET_NUMBER                 = saveData2 + 0x4E2
LM03_SET_NUMBER                 = saveData2 + 0x4E3
LM04_SET_NUMBER                 = saveData2 + 0x4E4
LM05_SET_NUMBER                 = saveData2 + 0x4E5
LM06_SET_NUMBER                 = saveData2 + 0x4E6
LM07_SET_NUMBER                 = saveData2 + 0x4E7
LM08_SET_NUMBER                 = saveData2 + 0x4E8
LM09_SET_NUMBER                 = saveData2 + 0x4E9
LM10_SET_NUMBER                 = saveData2 + 0x4EA
LM11_SET_NUMBER                 = saveData2 + 0x4EB
LM12_SET_NUMBER                 = saveData2 + 0x4EC
LM13_SET_NUMBER                 = saveData2 + 0x4ED
LM14_SET_NUMBER                 = saveData2 + 0x4EE
LM15_SET_NUMBER                 = saveData2 + 0x4EF
LM16_SET_NUMBER                 = saveData2 + 0x4F0
LM17_SET_NUMBER                 = saveData2 + 0x4F1
NM01_SET_NUMBER                 = saveData2 + 0x4F2
NM02_SET_NUMBER                 = saveData2 + 0x4F3
NM03_SET_NUMBER                 = saveData2 + 0x4F4
NM04_SET_NUMBER                 = saveData2 + 0x4F5
NM05_SET_NUMBER                 = saveData2 + 0x4F6
NM06_SET_NUMBER                 = saveData2 + 0x4F7
NM07_SET_NUMBER                 = saveData2 + 0x4F8
NM08_SET_NUMBER                 = saveData2 + 0x4F9
NM09_SET_NUMBER                 = saveData2 + 0x4FA
NM10_SET_NUMBER                 = saveData2 + 0x4FB
NM11_SET_NUMBER                 = saveData2 + 0x4FC
NM12_SET_NUMBER                 = saveData2 + 0x4FD
NM13_SET_NUMBER                 = saveData2 + 0x4FE
HE01_SET_NUMBER                 = saveData2 + 0x4FF
HE02_SET_NUMBER                 = saveData2 + 0x500
HE03_SET_NUMBER                 = saveData2 + 0x501
HE04_SET_NUMBER                 = saveData2 + 0x502
HE05_SET_NUMBER                 = saveData2 + 0x503
HE06_SET_NUMBER                 = saveData2 + 0x504
HE07_SET_NUMBER                 = saveData2 + 0x505
PI01_SET_NUMBER                 = saveData2 + 0x506
PI02_SET_NUMBER                 = saveData2 + 0x507
PI03_SET_NUMBER                 = saveData2 + 0x508
PI04_SET_NUMBER                 = saveData2 + 0x509
PI05_SET_NUMBER                 = saveData2 + 0x50A
PI06_SET_NUMBER                 = saveData2 + 0x50B
PI07_SET_NUMBER                 = saveData2 + 0x50C
PI08_SET_NUMBER                 = saveData2 + 0x50D
PI09_SET_NUMBER                 = saveData2 + 0x50E
PI10_SET_NUMBER                 = saveData2 + 0x50F
PI11_SET_NUMBER                 = saveData2 + 0x510
PP01_SET_NUMBER                 = saveData2 + 0x511
PP02_SET_NUMBER                 = saveData2 + 0x512
PP03_SET_NUMBER                 = saveData2 + 0x513
PP04_SET_NUMBER                 = saveData2 + 0x514
PP05_SET_NUMBER                 = saveData2 + 0x515
PP06_SET_NUMBER                 = saveData2 + 0x516
PP07_SET_NUMBER                 = saveData2 + 0x517
PP08_SET_NUMBER                 = saveData2 + 0x518
PP09_SET_NUMBER                 = saveData2 + 0x519
PP10_SET_NUMBER                 = saveData2 + 0x51A
PP11_SET_NUMBER                 = saveData2 + 0x51B
PP12_SET_NUMBER                 = saveData2 + 0x51C
PC01_SET_NUMBER                 = saveData2 + 0x51E
PC02_SET_NUMBER                 = saveData2 + 0x51F
PC03_SET_NUMBER                 = saveData2 + 0x520
PC04_SET_NUMBER                 = saveData2 + 0x521
PC05_SET_NUMBER                 = saveData2 + 0x522
LIBRARY_FLAG                    = saveData2 + 0x523
PC07_SET_NUMBER                 = saveData2 + 0x524
PC08_SET_NUMBER                 = saveData2 + 0x525
PC09_SET_NUMBER                 = saveData2 + 0x526
PC10_SET_NUMBER                 = saveData2 + 0x527
PC11_SET_NUMBER                 = saveData2 + 0x528
PC12_SET_NUMBER                 = saveData2 + 0x529
PC13_SET_NUMBER                 = saveData2 + 0x52A
PC14_SET_NUMBER                 = saveData2 + 0x52B
PC15_SET_NUMBER                 = saveData2 + 0x52C
PC16_SET_NUMBER                 = saveData2 + 0x52D
PC17_SET_NUMBER                 = saveData2 + 0x52E
EW01_SET_NUMBER                 = saveData2 + 0x52F
EW02_SET_NUMBER                 = saveData2 + 0x530
EW03_SET_NUMBER                 = saveData2 + 0x531
EW04_SET_NUMBER                 = saveData2 + 0x532
EW05_SET_NUMBER                 = saveData2 + 0x533
EW06_SET_NUMBER                 = saveData2 + 0x534
EW07_SET_NUMBER                 = saveData2 + 0x535
EW08_SET_NUMBER                 = saveData2 + 0x536
EW09_SET_NUMBER                 = saveData2 + 0x537
EW10_SET_NUMBER                 = saveData2 + 0x538
EW11_SET_NUMBER                 = saveData2 + 0x539
EW12_SET_NUMBER                 = saveData2 + 0x53A
EW13_SET_NUMBER                 = saveData2 + 0x53B
EW14_SET_NUMBER                 = saveData2 + 0x53C
EW15_SET_NUMBER                 = saveData2 + 0x53D
EW16_SET_NUMBER                 = saveData2 + 0x53E
EW17_SET_NUMBER                 = saveData2 + 0x53F
EW18_SET_NUMBER                 = saveData2 + 0x540
EW19_SET_NUMBER                 = saveData2 + 0x541
EW20_SET_NUMBER                 = saveData2 + 0x542
EW21_SET_NUMBER                 = saveData2 + 0x543
EW22_SET_NUMBER                 = saveData2 + 0x544
EW23_SET_NUMBER                 = saveData2 + 0x545
EW24_SET_NUMBER                 = saveData2 + 0x546
EW25_SET_NUMBER                 = saveData2 + 0x547
EW26_SET_NUMBER                 = saveData2 + 0x548
EW27_SET_NUMBER                 = saveData2 + 0x549
EW28_SET_NUMBER                 = saveData2 + 0x54A
EW29_SET_NUMBER                 = saveData2 + 0x54B
FINAL_REST                      = saveData2 + 0x54C
EW31_SET_NUMBER                 = saveData2 + 0x54D
EW32_SET_NUMBER                 = saveData2 + 0x54E
EW33_SET_NUMBER                 = saveData2 + 0x54F
EW34_SET_NUMBER                 = saveData2 + 0x550
EW35_SET_NUMBER                 = saveData2 + 0x551
EW36_SET_NUMBER                 = saveData2 + 0x552
EW37_SET_NUMBER                 = saveData2 + 0x553
EW38_SET_NUMBER                 = saveData2 + 0x554
EW39_SET_NUMBER                 = saveData2 + 0x555

-- single bits: ReadBit(NAME, NAME_BIT) / WriteBit(NAME, NAME_BIT, v); NAME_BIT counts from 1 (lowest bit)
OC_OLYMPIA_CHEST_OPENED, OC_OLYMPIA_CHEST_OPENED_BIT = saveData1 + 0x329, 2
BLUE_TRINITY_LEARNED, BLUE_TRINITY_LEARNED_BIT = saveData2 + 0x01B, 1
RED_TRINITY_LEARNED, RED_TRINITY_LEARNED_BIT = saveData2 + 0x01B, 2
GREEN_TRINITY_LEARNED, GREEN_TRINITY_LEARNED_BIT = saveData2 + 0x01B, 3
YELLOW_TRINITY_LEARNED, YELLOW_TRINITY_LEARNED_BIT = saveData2 + 0x01B, 4
WHITE_TRINITY_LEARNED, WHITE_TRINITY_LEARNED_BIT = saveData2 + 0x01B, 5
TW03_BLUE_TRINITY_DONE, TW03_BLUE_TRINITY_DONE_BIT = saveData2 + 0x06C, 4
TT_1ST_DISTRICT_BLUE_TRINITY_EXIT_DOOR, TT_1ST_DISTRICT_BLUE_TRINITY_EXIT_DOOR_BIT = saveData2 + 0x06C, 7
TW05_RED_TRINITY_DONE, TW05_RED_TRINITY_DONE_BIT = saveData2 + 0x06D, 8
WL_LOTUS_FOREST_BLUE_TRINITY_BOULDER, WL_LOTUS_FOREST_BLUE_TRINITY_BOULDER_BIT = saveData2 + 0x06E, 6
WL_LOTUS_FOREST_BLUE_TRINITY_ALCOVE, WL_LOTUS_FOREST_BLUE_TRINITY_ALCOVE_BIT = saveData2 + 0x06E, 7
OC_GATES_GREEN_TRINITY, OC_GATES_GREEN_TRINITY_BIT = saveData2 + 0x070, 4
DJ_TREETOP_GREEN_TRINITY, DJ_TREETOP_GREEN_TRINITY_BIT = saveData2 + 0x072, 4
AG_TREASURE_ROOM_RED_TRINITY, AG_TREASURE_ROOM_RED_TRINITY_BIT = saveData2 + 0x074, 4
AG_BAZAAR_BLUE_TRINITY, AG_BAZAAR_BLUE_TRINITY_BIT = saveData2 + 0x074, 7
MONSTRO_CHAMBER_5_BLUE_TRINITY, MONSTRO_CHAMBER_5_BLUE_TRINITY_BIT = saveData2 + 0x076, 4
MONSTRO_THROAT_BLUE_TRINITY, MONSTRO_THROAT_BLUE_TRINITY_BIT = saveData2 + 0x076, 5
MONSTRO_MOUTH_BLUE_TRINITY, MONSTRO_MOUTH_BLUE_TRINITY_BIT = saveData2 + 0x076, 6
MONSTRO_CHAMBER_6_WHITE_TRINITY, MONSTRO_CHAMBER_6_WHITE_TRINITY_BIT = saveData2 + 0x076, 8
HB_DUNGEON_BLUE_TRINITY, HB_DUNGEON_BLUE_TRINITY_BIT = saveData2 + 0x07B, 6
HB_GREAT_CREST_BLUE_TRINITY, HB_GREAT_CREST_BLUE_TRINITY_BIT = saveData2 + 0x07B, 7
DI_COCONUT_DROP_BLOCKED, DI_COCONUT_DROP_BLOCKED_BIT = saveData2 + 0x080, 8
TT_MAGICIAN_STUDY_BLUE_TRINITY, TT_MAGICIAN_STUDY_BLUE_TRINITY_BIT = saveData2 + 0x0B1, 1
TW05_RED_TRINITY_MARK_HIDDEN, TW05_RED_TRINITY_MARK_HIDDEN_BIT = saveData2 + 0x0B1, 6
TT_3RD_DISTRICT_BLUE_TRINITY, TT_3RD_DISTRICT_BLUE_TRINITY_BIT = saveData2 + 0x0B3, 4
TT_GIZMO_SHOP_POSTCARD_1, TT_GIZMO_SHOP_POSTCARD_1_BIT = saveData2 + 0x0BE, 6
TT_GIZMO_SHOP_POSTCARD_2, TT_GIZMO_SHOP_POSTCARD_2_BIT = saveData2 + 0x0BE, 7
TT_GEPPETTO_HOUSE_POSTCARD, TT_GEPPETTO_HOUSE_POSTCARD_BIT = saveData2 + 0x0C0, 4
TT_ITEM_WORKSHOP_POSTCARD, TT_ITEM_WORKSHOP_POSTCARD_BIT = saveData2 + 0x0C0, 5
TT_3RD_DISTRICT_BALCONY_POSTCARD, TT_3RD_DISTRICT_BALCONY_POSTCARD_BIT = saveData2 + 0x0C0, 7
TT_ITEM_SHOP_POSTCARD, TT_ITEM_SHOP_POSTCARD_BIT = saveData2 + 0x0C0, 8
WL_BIZARRE_ROOM_FLOWER_POT, WL_BIZARRE_ROOM_FLOWER_POT_BIT = saveData2 + 0x0E2, 8
WL_BIZARRE_ROOM_READ_BOOK, WL_BIZARRE_ROOM_READ_BOOK_BIT = saveData2 + 0x0E3, 8
WL_LOTUS_FOREST_RED_ETHER_FLOWER_ALONG_WALL, WL_LOTUS_FOREST_RED_ETHER_FLOWER_ALONG_WALL_BIT = saveData2 + 0x0E8, 2
WL_LOTUS_FOREST_RED_FLOWER_RAISE_LILY_PADS, WL_LOTUS_FOREST_RED_FLOWER_RAISE_LILY_PADS_BIT = saveData2 + 0x0E8, 3
WL_LOTUS_FOREST_RED_ETHER_FLOWER_ACROSS_FROM_QUEEN_S_CASTLE, WL_LOTUS_FOREST_RED_ETHER_FLOWER_ACROSS_FROM_QUEEN_S_CASTLE_BIT = saveData2 + 0x0E8, 5
WL_LOTUS_FOREST_YELLOW_POTION_FLOWER_THROUGH_PAINTING, WL_LOTUS_FOREST_YELLOW_POTION_FLOWER_THROUGH_PAINTING_BIT = saveData2 + 0x0E8, 6
WL_LOTUS_FOREST_YELLOW_ELIXIR_FLOWER_THROUGH_PAINTING, WL_LOTUS_FOREST_YELLOW_ELIXIR_FLOWER_THROUGH_PAINTING_BIT = saveData2 + 0x0E8, 7
WL_LOTUS_FOREST_YELLOW_POTION_FLOWER_IN_CENTER_ALCOVE, WL_LOTUS_FOREST_YELLOW_POTION_FLOWER_IN_CENTER_ALCOVE_BIT = saveData2 + 0x0E8, 8
WL_TEA_PARTY_RIGHT_YELLOW_CHAIR, WL_TEA_PARTY_RIGHT_YELLOW_CHAIR_BIT = saveData2 + 0x0F1, 2
WL_TEA_PARTY_RIGHT_BROWN_CHAIR, WL_TEA_PARTY_RIGHT_BROWN_CHAIR_BIT = saveData2 + 0x0F1, 4
WL_TEA_PARTY_LEFT_GRAY_CHAIR, WL_TEA_PARTY_LEFT_GRAY_CHAIR_BIT = saveData2 + 0x0F1, 5
WL_TEA_PARTY_LEFT_PINK_CHAIR, WL_TEA_PARTY_LEFT_PINK_CHAIR_BIT = saveData2 + 0x0F1, 6
WL_TEA_PARTY_LEFT_CUSHIONED_CHAIR, WL_TEA_PARTY_LEFT_CUSHIONED_CHAIR_BIT = saveData2 + 0x0F1, 7
EVIDENCE_BOX_ANTENNA_SECOND_BIT, EVIDENCE_BOX_ANTENNA_SECOND_BIT_BIT = saveData2 + 0x10E, 1
EVIDENCE_BOX_STENCH_SECOND_BIT, EVIDENCE_BOX_STENCH_SECOND_BIT_BIT = saveData2 + 0x10E, 2
EVIDENCE_BOX_CLAW_MARKS_SECOND_BIT, EVIDENCE_BOX_CLAW_MARKS_SECOND_BIT_BIT = saveData2 + 0x10E, 3
EVIDENCE_BOX_FOOTPRINTS_SECOND_BIT, EVIDENCE_BOX_FOOTPRINTS_SECOND_BIT_BIT = saveData2 + 0x10E, 4
EVIDENCE_BOX_ANTENNA_OPENED, EVIDENCE_BOX_ANTENNA_OPENED_BIT = saveData2 + 0x10E, 5
EVIDENCE_BOX_STENCH_OPENED, EVIDENCE_BOX_STENCH_OPENED_BIT = saveData2 + 0x10E, 6
EVIDENCE_BOX_CLAW_MARKS_OPENED, EVIDENCE_BOX_CLAW_MARKS_OPENED_BIT = saveData2 + 0x10E, 7
EVIDENCE_BOX_FOOTPRINTS_OPENED, EVIDENCE_BOX_FOOTPRINTS_OPENED_BIT = saveData2 + 0x10E, 8
ATLANTICA_CLAM_UNDERSEA_GORGE_BLIZZARD_CLAM, ATLANTICA_CLAM_UNDERSEA_GORGE_BLIZZARD_CLAM_BIT = saveData2 + 0x1A9, 1
ATLANTICA_CLAM_UNDERSEA_GORGE_OCEAN_FLOOR_CLAM, ATLANTICA_CLAM_UNDERSEA_GORGE_OCEAN_FLOOR_CLAM_BIT = saveData2 + 0x1A9, 2
ATLANTICA_CLAM_UNDERSEA_VALLEY_HIGHER_CAVE_CLAM, ATLANTICA_CLAM_UNDERSEA_VALLEY_HIGHER_CAVE_CLAM_BIT = saveData2 + 0x1A9, 3
ATLANTICA_CLAM_UNDERSEA_VALLEY_LOWER_CAVE_CLAM, ATLANTICA_CLAM_UNDERSEA_VALLEY_LOWER_CAVE_CLAM_BIT = saveData2 + 0x1A9, 4
ATLANTICA_CLAM_UNDERSEA_VALLEY_FIRE_CLAM, ATLANTICA_CLAM_UNDERSEA_VALLEY_FIRE_CLAM_BIT = saveData2 + 0x1A9, 5
ATLANTICA_CLAM_UNDERSEA_VALLEY_WALL_CLAM, ATLANTICA_CLAM_UNDERSEA_VALLEY_WALL_CLAM_BIT = saveData2 + 0x1A9, 6
ATLANTICA_CLAM_UNDERSEA_VALLEY_PILLAR_CLAM, ATLANTICA_CLAM_UNDERSEA_VALLEY_PILLAR_CLAM_BIT = saveData2 + 0x1A9, 7
ATLANTICA_CLAM_UNDERSEA_VALLEY_OCEAN_FLOOR_CLAM, ATLANTICA_CLAM_UNDERSEA_VALLEY_OCEAN_FLOOR_CLAM_BIT = saveData2 + 0x1A9, 8
ATLANTICA_CLAM_TRITON_S_PALACE_THUNDER_CLAM, ATLANTICA_CLAM_TRITON_S_PALACE_THUNDER_CLAM_BIT = saveData2 + 0x1AA, 1
ATLANTICA_CLAM_TRITON_S_PALACE_WALL_RIGHT_CLAM, ATLANTICA_CLAM_TRITON_S_PALACE_WALL_RIGHT_CLAM_BIT = saveData2 + 0x1AA, 2
ATLANTICA_CLAM_TRITON_S_PALACE_NEAR_PATH_CLAM, ATLANTICA_CLAM_TRITON_S_PALACE_NEAR_PATH_CLAM_BIT = saveData2 + 0x1AA, 3
ATLANTICA_CLAM_TRITON_S_PALACE_WALL_LEFT_CLAM, ATLANTICA_CLAM_TRITON_S_PALACE_WALL_LEFT_CLAM_BIT = saveData2 + 0x1AA, 4
ATLANTICA_CLAM_CAVERN_NOOK_CLAM, ATLANTICA_CLAM_CAVERN_NOOK_CLAM_BIT = saveData2 + 0x1AA, 5
ATLANTICA_CLAM_BELOW_DECK_CLAM, ATLANTICA_CLAM_BELOW_DECK_CLAM_BIT = saveData2 + 0x1AA, 6
ATLANTICA_CLAM_UNDERSEA_GARDEN_CLAM, ATLANTICA_CLAM_UNDERSEA_GARDEN_CLAM_BIT = saveData2 + 0x1AA, 7
ATLANTICA_CLAM_UNDERSEA_CAVE_CLAM, ATLANTICA_CLAM_UNDERSEA_CAVE_CLAM_BIT = saveData2 + 0x1AA, 8
HT_LAB_TORN_PAGE, HT_LAB_TORN_PAGE_BIT = saveData2 + 0x1D0, 1
HT_JACK_DOORBELL_RUNG, HT_JACK_DOORBELL_RUNG_BIT = saveData2 + 0x1D0, 2
MONSTRO_PARASITE_CAGE_1_FLAGS, MONSTRO_PARASITE_CAGE_1_FLAGS_BIT = saveData2 + 0x25E, 7
NL_CLOCK_TOWER_0800_DOOR_OPENED, NL_CLOCK_TOWER_0800_DOOR_OPENED_BIT = saveData2 + 0x261, 1
NL_CLOCK_TOWER_0700_DOOR_OPENED, NL_CLOCK_TOWER_0700_DOOR_OPENED_BIT = saveData2 + 0x261, 2
NL_CLOCK_TOWER_0600_DOOR_OPENED, NL_CLOCK_TOWER_0600_DOOR_OPENED_BIT = saveData2 + 0x261, 3
NL_CLOCK_TOWER_0500_DOOR_OPENED, NL_CLOCK_TOWER_0500_DOOR_OPENED_BIT = saveData2 + 0x261, 4
NL_CLOCK_TOWER_0400_DOOR_OPENED, NL_CLOCK_TOWER_0400_DOOR_OPENED_BIT = saveData2 + 0x261, 5
NL_CLOCK_TOWER_0300_DOOR_OPENED, NL_CLOCK_TOWER_0300_DOOR_OPENED_BIT = saveData2 + 0x261, 6
NL_CLOCK_TOWER_0200_DOOR_OPENED, NL_CLOCK_TOWER_0200_DOOR_OPENED_BIT = saveData2 + 0x261, 7
NL_CLOCK_TOWER_0100_DOOR_OPENED, NL_CLOCK_TOWER_0100_DOOR_OPENED_BIT = saveData2 + 0x261, 8
NL_HOLD_AERO_CHEST, NL_HOLD_AERO_CHEST_BIT = saveData2 + 0x262, 2
NL_CLOCK_TOWER_1200_DOOR_OPENED, NL_CLOCK_TOWER_1200_DOOR_OPENED_BIT = saveData2 + 0x262, 5
NL_CLOCK_TOWER_1100_DOOR_OPENED, NL_CLOCK_TOWER_1100_DOOR_OPENED_BIT = saveData2 + 0x262, 6
NL_CLOCK_TOWER_1000_DOOR_OPENED, NL_CLOCK_TOWER_1000_DOOR_OPENED_BIT = saveData2 + 0x262, 7
NL_CLOCK_TOWER_0900_DOOR_OPENED, NL_CLOCK_TOWER_0900_DOOR_OPENED_BIT = saveData2 + 0x262, 8
HB_LIFT_STOP_WATERWAY_NODE, HB_LIFT_STOP_WATERWAY_NODE_BIT = saveData2 + 0x295, 7
EOTW_HB_PORTAL_TO_CHERNABOG_PIT, EOTW_HB_PORTAL_TO_CHERNABOG_PIT_BIT = saveData2 + 0x2E8, 7
GUMMI_WARP_UNLOCKS, GUMMI_WARP_UNLOCKS_BIT = saveData2 + 0x2FF, 4
